title: Marina Espinoza
description: My personal website to showcase my artistic and code development sides.
theme: just-the-docs

url: https://mk-espinoza.github.io/

# Aux links
aux_links_new_tab: true
aux_links:
  GitHub: https://github.com/mk-espinoza
  LinkedIn: https://www.linkedin.com/in/mkespinoza/

# Search
search_enabled: false


